#!/bin/bash -e
# regenerate phorge secrets and mysql password

. /etc/default/inithooks

CONF=/opt/phorge/conf/custom/turnkey.conf.php

PASSWORD=$(mcookie)

sed -i "s/\('mysql.pass' =>\) .*,$/\1 '$PASSWORD',/" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=phorge --pass="$PASSWORD"
